
dofile(core.get_modpath("mydeck").."/joists.lua")
dofile(core.get_modpath("mydeck").."/deckboards.lua")
dofile(core.get_modpath("mydeck").."/piles.lua")
dofile(core.get_modpath("mydeck").."/rail.lua")
dofile(core.get_modpath("mydeck").."/machine.lua")
dofile(core.get_modpath("mydeck").."/beam.lua")
dofile(core.get_modpath("mydeck").."/stairs.lua")
dofile(core.get_modpath("mydeck").."/stain.lua")
dofile(core.get_modpath("mydeck").."/lattice.lua")
